# Generated by Django 2.2.4 on 2019-10-09 15:38

import chapeau.trilby_api.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilbyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('note', models.CharField(default='', max_length=255)),
                ('linked_url', models.URLField(default='', max_length=255)),
                ('moved_to', models.CharField(blank=True, default='', max_length=255)),
                ('_avatar', models.ImageField(blank=True, default=None, upload_to=chapeau.trilby_api.models.avatar_upload_to)),
                ('_header', models.ImageField(blank=True, default=None, upload_to=chapeau.trilby_api.models.header_upload_to)),
                ('public_key', models.CharField(editable=False, max_length=255)),
                ('private_key', models.CharField(editable=False, max_length=255)),
                ('default_sensitive', models.BooleanField(default=False)),
                ('default_visibility', models.CharField(choices=[('P', 'public'), ('X', 'private'), ('U', 'unlisted'), ('D', 'direct')], default='P', max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MessageCapturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('box', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('headers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sensitive', models.BooleanField(default=None)),
                ('spoiler_text', models.CharField(blank=True, default='', max_length=255)),
                ('visibility', models.CharField(choices=[('P', 'public'), ('X', 'private'), ('U', 'unlisted'), ('D', 'direct')], default=None, max_length=1)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('in_reply_to_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trilby_api.Status')),
                ('posted_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.AddField(
            model_name='trilbyuser',
            name='actor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trilby_api.Person'),
        ),
        migrations.AddField(
            model_name='trilbyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='trilbyuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
