# Generated by Django 3.0.4 on 2020-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterField(
            model_name='person',
            name='display_name',
            field=models.CharField(help_text='Your name, in human-friendly form. Something like "Alice Liddell".', max_length=255, verbose_name='display name'),
        ),
    ]
