# Generated by Django 2.2.4 on 2019-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0002_auto_20191009_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilbyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='trilbyuser',
            name='username',
            field=models.SlugField(max_length=254, unique=True, verbose_name='your username'),
        ),
    ]
