# Generated by Django 3.0.4 on 2020-04-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0002_auto_20200406_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='in_reply_to_id',
            new_name='in_reply_to',
        ),
    ]
