# Generated by Django 2.2.4 on 2019-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0003_auto_20191013_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilbyuser',
            name='username',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='your username'),
        ),
    ]
