# Generated by Django 2.2.4 on 2019-12-07 01:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kepi.trilby_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler_pub', '0003_auto_20191116_1539'),
        ('trilby_api', '0005_auto_20191013_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[(kepi.trilby_api.models.NotificationType('follow'), 'follow'), (kepi.trilby_api.models.NotificationType('mention'), 'mention'), (kepi.trilby_api.models.NotificationType('reblog'), 'reblog'), (kepi.trilby_api.models.NotificationType('favourite'), 'favourite')], max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bowler_pub.AcPerson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bowler_pub.AcItem')),
            ],
        ),
    ]
