# Generated by Django 2.2.4 on 2019-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0006_notification_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='about_account',
            field=models.CharField(default='', max_length=256),
        ),
    ]
