# Generated by Django 2.2.4 on 2019-12-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0007_notification_about_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='account',
            new_name='for_account',
        ),
    ]
