# Generated by Django 3.0.4 on 2020-04-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0007_auto_20200423_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='default_visibility',
            field=models.CharField(choices=[('A', 'public'), ('U', 'unlisted'), ('X', 'private'), ('D', 'direct')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='header_image',
            field=models.ImageField(blank=True, help_text="A large image, wider than it's tall, which appears at the top of your profile page.", null=True, upload_to='', verbose_name='header image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='A small square image used to identify you.', null=True, upload_to='', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='person',
            name='moved_to',
            field=models.URLField(blank=True, default=True, help_text='If set, the account has moved away, and this is where it went.', max_length=255, null=True),
        ),
    ]
