# Generated by Django 2.2.4 on 2019-12-18 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0008_auto_20191218_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
