# Generated by Django 2.2.4 on 2020-03-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0009_auto_20191218_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('remote_username', models.CharField(blank=True, max_length=255, null=True)),
                ('icon_image', models.ImageField(help_text='A small square image used to identify you.', null=True, upload_to='', verbose_name='icon')),
                ('header_image', models.ImageField(help_text="A large image, wider than it's tall, which appears at the top of your profile page.", null=True, upload_to='', verbose_name='header image')),
                ('display_name', models.TextField(help_text='Your name, in human-friendly form. Something like "Alice Liddell".', verbose_name='display name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicKey', models.TextField(blank=True, null=True, verbose_name='public key')),
                ('privateKey', models.TextField(blank=True, null=True, verbose_name='private key')),
                ('note', models.TextField(default='', help_text='Your biography. Something like "I enjoy falling down rabbitholes."', max_length=255, verbose_name='bio')),
                ('auto_follow', models.BooleanField(default=True, help_text='If True, follow requests will be accepted automatically.')),
            ],
        ),
        migrations.RemoveField(
            model_name='trilbyuser',
            name='actor',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensitive', models.BooleanField()),
                ('spoiler_text', models.CharField(max_length=255)),
                ('visibility', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Person')),
                ('in_reply_to_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Status')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='local_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
