# Generated by Django 2.2.4 on 2020-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0010_auto_20200316_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='in_reply_to_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Status'),
        ),
    ]
