# Generated by Django 2.2.4 on 2020-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0011_auto_20200320_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='remote_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
