# Generated by Django 3.0.4 on 2020-05-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0011_auto_20200514_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteperson',
            name='found_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (200, 'found'), (404, 'not found'), (410, 'gone'), (500, 'remote error')], default=0),
        ),
    ]
