# Generated by Django 3.0.4 on 2020-05-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0012_auto_20200516_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='default_sensitive',
        ),
        migrations.RemoveField(
            model_name='person',
            name='default_visibility',
        ),
        migrations.RemoveField(
            model_name='person',
            name='language',
        ),
        migrations.RemoveField(
            model_name='remoteperson',
            name='hostname',
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='acct',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
