# Generated by Django 3.0.4 on 2020-05-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0013_auto_20200516_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteperson',
            name='acct',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='remoteperson',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
