# Generated by Django 2.2.4 on 2020-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0013_person_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='moved_to',
            field=models.URLField(blank=True, default=True, help_text='If set, this account has moved away, and this is where it went.', max_length=255, null=True),
        ),
    ]
