# Generated by Django 3.0.4 on 2020-05-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0014_auto_20200516_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteperson',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
