# Generated by Django 2.2.4 on 2020-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0014_person_moved_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bot',
            field=models.BooleanField(default=False, help_text="If True, this account is a bot. If False, it's a human."),
        ),
    ]
