# Generated by Django 3.0.4 on 2020-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0015_remoteperson_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteperson',
            name='header_image',
            field=models.ImageField(blank=True, help_text="A large image, wider than it's tall, which appears at the top of your profile page.", null=True, upload_to='', verbose_name='header image'),
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='A small square image used to identify you.', null=True, upload_to='', verbose_name='icon'),
        ),
    ]
