# Generated by Django 2.2.4 on 2020-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0015_person_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='idempotency_key',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='language',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='spoiler_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
