# Generated by Django 2.2.4 on 2020-03-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0016_auto_20200327_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Person'),
        ),
    ]
