# Generated by Django 3.0.4 on 2020-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0017_person_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='localperson',
            name='default_visibility',
            field=models.CharField(choices=[('A', 'public'), ('U', 'unlisted'), ('X', 'private'), ('D', 'direct')], default='A', help_text="Default visibility.\n\nPublic (A): visible to anyone.\nUnlisted (U): visible to anyone, but doesn't appear in timelines.\nPrivate (X): only visible to followers.\nDirect (D): visible to nobody except tagged people.\n\nAdditionally, a person tagged in a status can\nalways view that status.", max_length=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.CharField(choices=[('A', 'public'), ('U', 'unlisted'), ('X', 'private'), ('D', 'direct')], default='A', help_text="Visiblity of this status.\n\nPublic (A): visible to anyone.\nUnlisted (U): visible to anyone, but doesn't appear in timelines.\nPrivate (X): only visible to followers.\nDirect (D): visible to nobody except tagged people.\n\nAdditionally, a person tagged in a status can\nalways view that status.", max_length=1),
        ),
    ]
