# Generated by Django 3.0.4 on 2020-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0018_auto_20200603_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='localperson',
            name='default_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
