# Generated by Django 2.2.4 on 2020-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0018_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('liker', 'liked'), name='i_cant_like_this_enough'),
        ),
    ]
