# Generated by Django 2.2.4 on 2020-03-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0019_auto_20200328_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='about_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_about', to='trilby_api.Person'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='for_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_for', to='trilby_api.Person'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('F', 'follow'), ('M', 'mention'), ('R', 'reblog'), ('L', 'favourite')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Status'),
        ),
    ]
