# Generated by Django 3.0.9 on 2020-08-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trilby_api', '0019_localperson_default_sensitive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localperson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AlterModelOptions(
            name='remoteperson',
            options={},
        ),
        migrations.AddField(
            model_name='status',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_trilby_api.status_set+', to='contenttypes.ContentType'),
        ),
    ]
