# Generated by Django 3.0.9 on 2020-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0020_auto_20200815_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localperson',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='remoteperson',
            options={'base_manager_name': 'objects'},
        ),
    ]
