# Generated by Django 2.2.4 on 2020-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0021_auto_20200330_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='default_visibility',
            field=models.CharField(default='public', max_length=255),
        ),
    ]
