# Generated by Django 3.0.9 on 2020-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0021_auto_20200820_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteperson',
            old_name='inbox',
            new_name='inbox_url',
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='featured_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='followers_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='following_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='remoteperson',
            name='outbox_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
