# Generated by Django 2.2.4 on 2020-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0022_person_default_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='default_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
