# Generated by Django 3.0.9 on 2020-09-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0022_auto_20200915_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='requested',
        ),
        migrations.AddField(
            model_name='follow',
            name='offer',
            field=models.URLField(blank=True, default=None, help_text="If this is an offer, the ID of the offer. If this isn't an offer, None.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(help_text="The person who's following.", on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_following', to='trilby_api.Person'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(help_text="The person who's being followed.", on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_followers', to='trilby_api.Person'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='show_reblogs',
            field=models.BooleanField(default=True, help_text="True if the following person wants to see reblogs from the follower. False if they only want to see the follower's original posts."),
        ),
    ]
