# Generated by Django 3.0.9 on 2020-10-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0023_auto_20200928_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='localperson',
            name='featured',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trilby_api.Status'),
        ),
    ]
