# Generated by Django 2.2.4 on 2020-03-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0023_person_default_sensitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
