# Generated by Django 3.0.9 on 2020-10-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0024_localperson_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications_for', to='trilby_api.LocalPerson'),
        ),
    ]
