# Generated by Django 2.2.4 on 2020-03-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0025_auto_20200331_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='spoiler_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.CharField(default='', max_length=255),
        ),
    ]
