# Generated by Django 3.0.9 on 2020-10-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0025_auto_20201011_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteperson',
            old_name='url',
            new_name='remote_url',
        ),
        migrations.RemoveField(
            model_name='remoteperson',
            name='status',
        ),
    ]
