# Generated by Django 2.2.4 on 2020-03-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0026_auto_20200331_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.CharField(default='public', max_length=255),
        ),
    ]
