# Generated by Django 3.0.9 on 2020-10-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0026_auto_20201019_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='localperson',
            name='gone',
            field=models.BooleanField(default=False, help_text='If True, the user has gone away.'),
        ),
    ]
