# Generated by Django 3.0.4 on 2020-04-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0027_auto_20200331_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='default_visibility',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='visibility',
            field=models.CharField(default='A', help_text="Visiblity of this status.\n\n            Public (A): visible to anyone.\n            Unlisted (U): visible to anyone, but\n                doesn't appear in timelines.\n            Private (X): only visible to followers.\n            Direct (D): visible to nobody except tagged people.\n\n            Additionally, a person tagged in a status can\n            always view that status.", max_length=1),
        ),
    ]
