# Generated by Django 3.0.9 on 2021-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilby_api', '0028_mention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='spoiler_text',
            new_name='spoiler_source',
        ),
        migrations.RemoveField(
            model_name='status',
            name='content',
        ),
        migrations.AddField(
            model_name='status',
            name='content_as_html_denormed',
            field=models.TextField(default=None, editable=False, help_text='HTML rendering of content_source. Do not edit!', null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='content_source',
            field=models.TextField(default='', help_text='Text of the status, as entered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='spoiler_as_html_denormed',
            field=models.CharField(default=None, editable=False, max_length=255, null=True),
        ),
    ]
