# Generated by Django 3.0.7 on 2020-07-27 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sombrero_sendpub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebfingerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('hostname', models.CharField(max_length=256)),
                ('activity_address', models.URLField(blank=True, default=None, null=True)),
                ('fetched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name='webfingeruser',
            constraint=models.UniqueConstraint(fields=('username', 'hostname'), name='user_and_host'),
        ),
    ]
