# Generated by Django 3.0.7 on 2020-07-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sombrero_sendpub', '0002_auto_20200727_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webfingeruser',
            old_name='activity_address',
            new_name='url',
        ),
    ]
