# Generated by Django 3.0.9 on 2020-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sombrero_sendpub', '0003_auto_20200730_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('status', models.IntegerField()),
                ('found_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
