# Generated by Django 2.0.6 on 2018-08-12 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_kepi', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('activity_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_kepi.ActivityObject')),
            ],
        ),
    ]
