# Generated by Django 2.1.1 on 2018-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinguser',
            name='remote',
            field=models.BooleanField(default=True),
        ),
    ]
