# Generated by Django 2.1 on 2018-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0002_thingarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinguser',
            name='favourite_colour',
            field=models.CharField(default='chartreuse', max_length=256),
        ),
        migrations.AlterField(
            model_name='thinguser',
            name='name',
            field=models.URLField(max_length=256),
        ),
    ]
