# Generated by Django 2.1.1 on 2018-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0003_thingarticle_remote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinguser',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
