# Generated by Django 2.1 on 2018-09-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0008_auto_20180830_1354'),
        ('things_for_testing', '0003_auto_20180829_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinguser',
            name='id',
        ),
        migrations.AddField(
            model_name='thinguser',
            name='actor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_kepi.Actor'),
            preserve_default=False,
        ),
    ]
