# Generated by Django 2.1.2 on 2018-10-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0004_auto_20181008_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinguser',
            name='remote',
        ),
        migrations.AddField(
            model_name='thinguser',
            name='url',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
