# Generated by Django 2.1 on 2018-09-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0004_auto_20180901_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinguser',
            name='actor',
        ),
        migrations.AddField(
            model_name='thinguser',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
