# Generated by Django 2.1.5 on 2019-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0005_auto_20181029_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThingArticle',
            new_name='ThingNote',
        ),
    ]
