# Generated by Django 2.1 on 2018-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0005_auto_20180912_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinguser',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
