# Generated by Django 2.1.5 on 2019-04-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0012_activitymodel'),
        ('things_for_testing', '0006_auto_20190423_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingnote',
            name='id',
        ),
        migrations.AddField(
            model_name='thingnote',
            name='activitymodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_kepi.ActivityModel'),
            preserve_default=False,
        ),
    ]
