# Generated by Django 2.1.5 on 2019-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0007_auto_20190423_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='thingnote',
            name='owner',
            field=models.URLField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
