# Generated by Django 2.1.5 on 2019-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0009_thinguser_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinguser',
            name='private_key',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
