# Generated by Django 2.1.5 on 2019-05-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0010_thinguser_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinguser',
            name='url',
        ),
    ]
