# Generated by Django 2.1.5 on 2019-05-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things_for_testing', '0011_remove_thinguser_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thingnote',
            name='activitymodel_ptr',
        ),
        migrations.DeleteModel(
            name='ThingUser',
        ),
        migrations.DeleteModel(
            name='ThingNote',
        ),
    ]
