# Generated by Django 2.0.6 on 2018-08-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.CharField(default='Object', max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
