# Generated by Django 2.2.4 on 2019-09-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acactor',
            name='f_preferredUsername',
        ),
    ]
