# Generated by Django 2.1.2 on 2018-10-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='accepted',
            new_name='pending',
        ),
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='f_type',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('P', 'p Update'), ('D', 'Delete'), ('F', 'Follow'), ('+', 'Add'), ('-', 'Remove'), ('L', 'Like'), ('U', 'Undo'), ('A', 'Accept'), ('R', 'Reject')], max_length=1),
        ),
    ]
