# Generated by Django 2.2.1 on 2019-07-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_kepi.Item')),
                ('to_actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_kepi.Actor')),
            ],
        ),
    ]
