# Generated by Django 2.2.1 on 2019-08-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='f_privateKey',
            new_name='privateKey',
        ),
    ]
