# Generated by Django 2.2.4 on 2019-09-13 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('django_kepi', '0002_acobject_published'), ('django_kepi', '0003_auto_20190913_2151')]

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acobject',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
