# Generated by Django 2.2.1 on 2019-05-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_kepi.Thing')),
                ('privateKey', models.TextField()),
                ('publicKey', models.TextField()),
                ('auto_follow', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thing',
            name='f_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Remove', 'Remove'), ('Reject', 'Reject'), ('Create', 'Create'), ('Update', 'Update'), ('Like', 'Like'), ('Add', 'Add'), ('Accept', 'Accept'), ('Delete', 'Delete'), ('Undo', 'Undo')], max_length=255),
        ),
    ]
