# Generated by Django 2.1 on 2018-09-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='actor',
            new_name='f_actor',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='fobject',
            new_name='f_object',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='fobject_type',
            new_name='f_object_type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='target',
            new_name='f_target',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='atype',
            new_name='f_type',
        ),
    ]
