# Generated by Django 2.2.1 on 2019-07-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fetch',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime)),
            ],
        ),
        migrations.DeleteModel(
            name='CachedRemoteText',
        ),
    ]
