# Generated by Django 2.1 on 2018-09-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_auto_20180916_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='f_type',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete'), ('F', 'Follow'), ('+', 'Add'), ('-', 'Remove'), ('L', 'Like'), ('U', 'Undo'), ('A', 'Accept'), ('R', 'Reject')], max_length=1),
        ),
    ]
