# Generated by Django 2.0.6 on 2018-08-19 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_auto_20180819_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accept',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='add',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='create',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='delete',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='like',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='reject',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='remove',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='tombstone',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='undo',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
        migrations.AlterField(
            model_name='update',
            name='register',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Register'),
        ),
    ]
