# Generated by Django 2.2.1 on 2019-08-10 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_auto_20190809_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetch',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
