# Generated by Django 2.1 on 2018-08-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_actor_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='django_kepi.Actor')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='django_kepi.Actor')),
            ],
        ),
    ]
