# Generated by Django 2.2.4 on 2019-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0002_remove_acactor_f_preferredusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='acactor',
            name='f_name',
            field=models.TextField(default='', help_text='Your name, in human-friendly form. Something like "Alice Liddell".', verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acobject',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acactor',
            name='f_summary',
            field=models.TextField(default='', help_text='Your biography. Something like "I enjoy falling down rabbitholes."', max_length=255, verbose_name='bio'),
        ),
    ]
