# Generated by Django 2.1.1 on 2018-09-23 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0003_auto_20180918_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedMessageNeeds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needs_to_fetch', models.URLField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kepi.QuarantinedMessage')),
            ],
        ),
    ]
