# Generated by Django 2.2.1 on 2019-06-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_kepi', '0003_auto_20190604_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='thing',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='thing',
        ),
        migrations.AddField(
            model_name='actor',
            name='thing_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_kepi.Thing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_kepi.thing_set+', to='contenttypes.ContentType'),
        ),
    ]
