# Generated by Django 2.2.1 on 2019-07-04 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0003_auto_20190704_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetch',
            name='date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
