# Generated by Django 2.2.1 on 2019-08-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0003_auto_20190810_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmessage',
            name='digest',
        ),
        migrations.RemoveField(
            model_name='incomingmessage',
            name='waiting_for',
        ),
    ]
