# Generated by Django 2.0.6 on 2018-08-19 18:07

from django.db import migrations, models
import django_kepi.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0003_auto_20180819_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='accept',
            name='id',
        ),
        migrations.RemoveField(
            model_name='accept',
            name='register',
        ),
        migrations.RemoveField(
            model_name='add',
            name='id',
        ),
        migrations.RemoveField(
            model_name='add',
            name='register',
        ),
        migrations.RemoveField(
            model_name='create',
            name='id',
        ),
        migrations.RemoveField(
            model_name='create',
            name='register',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='register',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='register',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='register',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reject',
            name='register',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='id',
        ),
        migrations.RemoveField(
            model_name='remove',
            name='register',
        ),
        migrations.RemoveField(
            model_name='tombstone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tombstone',
            name='register',
        ),
        migrations.RemoveField(
            model_name='undo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='undo',
            name='register',
        ),
        migrations.RemoveField(
            model_name='update',
            name='id',
        ),
        migrations.RemoveField(
            model_name='update',
            name='register',
        ),
        migrations.AddField(
            model_name='accept',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='add',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='create',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='delete',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='follow',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='like',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reject',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='remove',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tombstone',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='undo',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='update',
            name='numeric_id',
            field=models.PositiveIntegerField(default=django_kepi.models.Cobject.random_number, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
