# Generated by Django 2.1 on 2018-08-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0003_blocking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocking',
            old_name='follower',
            new_name='blocker',
        ),
        migrations.RenameField(
            model_name='blocking',
            old_name='following',
            new_name='blocking',
        ),
    ]
