# Generated by Django 2.1.1 on 2018-09-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0004_quarantinedmessageneeds'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='quarantinedmessageneeds',
            index_together={('message', 'needs_to_fetch')},
        ),
    ]
