# Generated by Django 2.2.1 on 2019-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0004_auto_20190812_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='digest',
            field=models.CharField(default='', max_length=255),
        ),
    ]
