# Generated by Django 2.2.1 on 2019-07-08 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0004_auto_20190704_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='f_attributedTo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fetch',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
