# Generated by Django 2.0.6 on 2018-08-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0004_auto_20180819_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accept',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='create',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='delete',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='reject',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='remove',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tombstone',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='undo',
            old_name='numeric_id',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='numeric_id',
            new_name='slug',
        ),
    ]
