# Generated by Django 2.1.5 on 2019-02-13 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedText',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.URLField()),
                ('contents', models.TextField()),
            ],
        ),
    ]
