# Generated by Django 2.1.5 on 2019-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0005_cachedtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedtext',
            name='contents',
            field=models.TextField(default=None, null=True),
        ),
    ]
