# Generated by Django 2.2.1 on 2019-07-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0005_auto_20190708_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='to_actor',
            field=models.CharField(max_length=255),
        ),
    ]
