# Generated by Django 2.2.1 on 2019-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0005_incomingmessage_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='remote_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
