# Generated by Django 2.1 on 2018-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0005_requestingaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.URLField(max_length=256),
        ),
    ]
