# Generated by Django 2.2.1 on 2019-08-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0006_auto_20190814_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='from_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_kepi.Object'),
        ),
    ]
