# Generated by Django 2.1.5 on 2019-04-07 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0006_auto_20190216_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.URLField()),
                ('key', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('digest', models.CharField(default='', max_length=255)),
                ('host', models.CharField(default='', max_length=255)),
                ('signature', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('actor', models.CharField(default='', max_length=255)),
                ('key_id', models.CharField(default='', max_length=255)),
                ('waiting_for', models.URLField(default=None)),
            ],
        ),
    ]
