# Generated by Django 2.1 on 2018-08-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0006_auto_20180829_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='url',
        ),
    ]
