# Generated by Django 2.1.5 on 2019-04-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0007_cachedpublickey_incomingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
