# Generated by Django 2.2.1 on 2019-07-11 17:08

from django.db import migrations, models
import django_kepi.models.thing


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0008_auto_20190711_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='f_actor',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='f_name',
        ),
        migrations.AlterField(
            model_name='thing',
            name='number',
            field=models.CharField(default=django_kepi.models.thing._new_number, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='other_fields',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='thing',
            name='remote_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
