# Generated by Django 2.1.5 on 2019-04-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0008_incomingmessage_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachedText',
        ),
        migrations.AlterIndexTogether(
            name='quarantinedmessageneeds',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='quarantinedmessageneeds',
            name='message',
        ),
        migrations.RemoveField(
            model_name='incomingmessage',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='incomingmessage',
            name='key_id',
        ),
        migrations.DeleteModel(
            name='QuarantinedMessage',
        ),
        migrations.DeleteModel(
            name='QuarantinedMessageNeeds',
        ),
    ]
