# Generated by Django 2.1 on 2018-09-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_kepi', '0008_auto_20180830_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedObject',
            fields=[
                ('url', models.URLField(max_length=255, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField(default=None)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
