# Generated by Django 2.2.1 on 2019-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0009_auto_20190711_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='privateKey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='publicKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
