# Generated by Django 2.1 on 2018-09-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0009_namedobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedobject',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='NamedObject',
        ),
    ]
