# Generated by Django 2.1.5 on 2019-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0009_auto_20190410_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='waiting_for',
            field=models.URLField(default=None, null=True),
        ),
    ]
