# Generated by Django 2.2.1 on 2019-07-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0010_auto_20190711_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='privateKey',
            new_name='f_privateKey',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='publicKey',
            new_name='f_publicKey',
        ),
    ]
