# Generated by Django 2.1 on 2018-09-07 19:50

from django.db import migrations, models
import django_kepi.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0010_auto_20180906_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('atype', models.URLField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete'), ('F', 'Follow'), ('+', 'Add'), ('-', 'Remove'), ('L', 'Like'), ('U', 'Undo'), ('A', 'Accept'), ('R', 'Reject')], max_length=1)),
                ('identifier', models.URLField(default=django_kepi.models.new_activity_identifier, max_length=255, primary_key=True, serialize=False)),
                ('actor', models.URLField(blank=True, max_length=255)),
                ('fobject_type', models.CharField(blank=True, max_length=255)),
                ('fobject', models.URLField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
