# Generated by Django 2.1 on 2018-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0011_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='target',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
