# Generated by Django 2.2.1 on 2019-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0011_auto_20190718_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='is_local_user',
            field=models.BooleanField(default=False),
        ),
    ]
