# Generated by Django 2.1.5 on 2019-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0012_activitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedRemoteText',
            fields=[
                ('address', models.URLField(primary_key=True, serialize=False)),
                ('content', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CachedRemoteUser',
        ),
    ]
