# Generated by Django 2.1 on 2018-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0012_activity_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=255)),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('signature_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
