# Generated by Django 2.2.1 on 2019-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0012_incomingmessage_is_local_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='f_actor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
