# Generated by Django 2.1 on 2018-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0013_quarantinedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinedmessage',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
