# Generated by Django 2.1.5 on 2019-05-01 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0013_auto_20190428_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='identifier',
            field=models.URLField(max_length=255),
        ),
    ]
