# Generated by Django 2.1.5 on 2019-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0014_auto_20190501_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='uuid',
        ),
        migrations.AddField(
            model_name='activity',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='remote_url',
            field=models.URLField(default=None, max_length=255, unique=True),
        ),
    ]
