# Generated by Django 2.2.1 on 2019-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0014_auto_20190726_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='target_collection',
            field=models.CharField(default='', max_length=255),
        ),
    ]
