# Generated by Django 2.1.5 on 2019-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0015_auto_20190503_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='remote_url',
            field=models.URLField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
