# Generated by Django 2.2.1 on 2019-07-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0015_incomingmessage_target_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmessage',
            name='target_collection',
        ),
    ]
