# Generated by Django 2.2.1 on 2019-08-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0016_remove_incomingmessage_target_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='other_fields',
        ),
        migrations.CreateModel(
            name='ThingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_kepi.Thing')),
            ],
        ),
        migrations.AddConstraint(
            model_name='thingfield',
            constraint=models.UniqueConstraint(fields=('parent', 'field'), name='parent_field'),
        ),
    ]
