# Generated by Django 2.1.5 on 2019-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0017_auto_20190503_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='pending',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='source',
        ),
        migrations.AddField(
            model_name='activity',
            name='other_fields',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
