# Generated by Django 2.1.5 on 2019-05-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0018_auto_20190511_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='f_object',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='f_object_type',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='f_target',
        ),
    ]
