# Generated by Django 2.1.5 on 2019-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0019_auto_20190511_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='f_type',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('P', 'p Update'), ('D', 'Delete'), ('F', 'Follow'), ('+', 'Add'), ('-', 'Remove'), ('L', 'Like'), ('U', 'Undo'), ('A', 'Accept'), ('R', 'Reject')], max_length=255),
        ),
    ]
