# Generated by Django 2.1.5 on 2019-05-18 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0021_auto_20190516_1515'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Thing',
        ),
        migrations.AlterField(
            model_name='ActivityField',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kepi.Thing'),
        ),
        migrations.RenameModel(
            old_name='ActivityField',
            new_name='ThingField',
        ),
    ]
