# Generated by Django 2.1.5 on 2019-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0022_auto_20190518_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='f_type',
            field=models.CharField(choices=[('Remove', 'Remove'), ('Update', 'Update'), ('Reject', 'Reject'), ('Undo', 'Undo'), ('Accept', 'Accept'), ('Create', 'Create'), ('Like', 'Like'), ('Follow', 'Follow'), ('Delete', 'Delete'), ('Add', 'Add')], max_length=255),
        ),
    ]
