# Generated by Django 2.1.5 on 2019-05-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0023_auto_20190518_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='f_type',
            field=models.CharField(choices=[('Delete', 'Delete'), ('Accept', 'Accept'), ('Like', 'Like'), ('Remove', 'Remove'), ('Follow', 'Follow'), ('Undo', 'Undo'), ('Update', 'Update'), ('Add', 'Add'), ('Create', 'Create'), ('Reject', 'Reject')], max_length=255),
        ),
    ]
