# Generated by Django 2.1.5 on 2019-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0025_auto_20190518_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.URLField(max_length=255)),
                ('following', models.URLField(max_length=255)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thing',
            name='f_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Add', 'Add'), ('Create', 'Create'), ('Like', 'Like'), ('Undo', 'Undo'), ('Reject', 'Reject'), ('Delete', 'Delete'), ('Remove', 'Remove'), ('Accept', 'Accept'), ('Update', 'Update')], max_length=255),
        ),
    ]
