# Generated by Django 2.1.5 on 2019-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_kepi', '0026_auto_20190518_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='f_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thing',
            name='f_type',
            field=models.CharField(choices=[('Undo', 'Undo'), ('Like', 'Like'), ('Delete', 'Delete'), ('Remove', 'Remove'), ('Create', 'Create'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Follow', 'Follow'), ('Add', 'Add'), ('Update', 'Update')], max_length=255),
        ),
    ]
