# Generated by Django 3.0.4 on 2020-05-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowler_pub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fetch',
        ),
    ]
