# Generated by Django 2.2.4 on 2020-02-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler_pub', '0003_auto_20191116_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acitem',
            name='serial',
        ),
        migrations.AddField(
            model_name='acobject',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
