# Generated by Django 2.2.4 on 2020-02-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler_pub', '0004_auto_20200204_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='acactivity',
            name='f_object',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
