# Generated by Django 2.2.4 on 2019-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowler_pub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acitem',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
